on:
  workflow_dispatch:
  push:
  pull_request:

name: Test

permissions:
  contents: read

jobs:
  docker:
    name: Docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Configuration
        id: configuration
        uses: ./
        with:
          schema: docker
          path: tests/docker.yml